In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/cs_students.csv")

In [2]:
df.shape

(180, 12)

In [3]:
df.head()

,Student ID,Name,Gender,Age,GPA,Major,Interested Domain,Projects,Future Career,Python,SQL,Java
0,1,John Smith,Male,21,3.5,Computer Science,Artificial Intelligence,Chatbot Development,Machine Learning Researcher,Strong,Strong,Weak
1,2,Alice Johnson,Female,20,3.2,Computer Science,Data Science,Data Analytics,Data Scientist,Average,Strong,Weak
2,3,Robert Davis,Male,22,3.8,Computer Science,Software Development,E-commerce Website,Software Engineer,Strong,Strong,Average
3,4,Emily Wilson,Female,21,3.7,Computer Science,Web Development,Full-Stack Web App,Web Developer,Weak,Strong,Strong
4,5,Michael Brown,Male,23,3.4,Computer Science,Cybersecurity,Network Security,Information Security Analyst,Average,Weak,Strong

In [4]:
df.dtypes

Student ID             int64
Name                     str
Gender                   str
Age                    int64
GPA                  float64
Major                    str
Interested Domain        str
Projects                 str
Future Career            str
Python                   str
SQL                      str
Java                     str
dtype: object

In [5]:
df["Future Career"].value_counts()

Future Career
Web Developer                   19
Information Security Analyst    17
Mobile App Developer            17
Database Administrator          16
Cloud Solutions Architect       16
Software Engineer               14
Machine Learning Engineer       13
NLP Research Scientist          11
Graphics Programmer              9
Data Scientist                   8
Data Analyst                     6
AI Researcher                    6
Game Developer                   4
Bioinformatician                 2
UX Designer                      2
Healthcare IT Specialist         2
Quantum Computing Researcher     2
Machine Learning Researcher      1
Security Analyst                 1
Embedded Software Engineer       1
Robotics Engineer                1
Ethical Hacker                   1
Computer Vision Engineer         1
DevOps Engineer                  1
IoT Developer                    1
NLP Engineer                     1
VR Developer                     1
Blockchain Engineer              1
SEO Specialist                   1
Data Privacy Specialist          1
Geospatial Analyst               1
Distributed Systems Engineer     1
Digital Forensics Specialist     1
Name: count, dtype: int64

In [6]:
df.isnull().sum()

Student ID           0
Name                 0
Gender               0
Age                  0
GPA                  0
Major                0
Interested Domain    0
Projects             0
Future Career        0
Python               0
SQL                  0
Java                 0
dtype: int64

In [7]:
df["Major"].value_counts()

Major
Computer Science    180
Name: count, dtype: int64

In [8]:
df["Interested Domain"].value_counts()

Interested Domain
Artificial Intelligence           19
Web Development                   19
Cybersecurity                     18
Mobile App Development            17
Database Management               16
Cloud Computing                   16
Data Science                      13
Machine Learning                  13
Computer Graphics                 13
Software Development              11
Software Engineering               5
Bioinformatics                     2
Human-Computer Interaction         2
Biomedical Computing               2
Quantum Computing                  2
Network Security                   1
Game Development                   1
Computer Vision                    1
IoT (Internet of Things)           1
Natural Language Processing        1
Data Mining                        1
Blockchain Technology              1
Information Retrieval              1
Data Privacy                       1
Geographic Information Systems     1
Distributed Systems                1
Digital Forensics                  1
Name: count, dtype: int64

In [9]:
df["Age"].describe()

count    180.000000
mean      22.116667
std        2.823040
min       20.000000
25%       21.000000
50%       22.000000
75%       22.250000
max       37.000000
Name: Age, dtype: float64

In [10]:
import sys
sys.path.append("..")

from src.career_mapping import CAREER_FAMILY

df["Career Family"] = df["Future Career"].map(CAREER_FAMILY)
df["Career Family"].value_counts()

Career Family
Data & AI                 47
Web & Software            36
Infrastructure & Cloud    34
Mobile & Games            31
Security                  21
Specialized & Emerging    11
Name: count, dtype: int64

In [11]:
df["Career Family"].isnull().sum()

np.int64(0)

In [12]:
features = ["GPA", "Interested Domain", "Projects", "Python", "SQL", "Java"]
target = "Career Family"

X = df[features]
y = df[target]

X.head()

   GPA        Interested Domain             Projects   Python     SQL     Java
0  3.5  Artificial Intelligence  Chatbot Development   Strong  Strong     Weak
1  3.2             Data Science       Data Analytics  Average  Strong     Weak
2  3.8     Software Development   E-commerce Website   Strong  Strong  Average
3  3.7          Web Development   Full-Stack Web App     Weak  Strong   Strong
4  3.4            Cybersecurity     Network Security  Average    Weak   Strong

In [13]:
X["Interested Domain"].nunique(), X["Projects"].nunique()

(27, 65)

In [14]:
features = ["GPA", "Interested Domain", "Python", "SQL", "Java"]

X = df[features].copy()
y = df["Career Family"]

In [15]:
counts = X["Interested Domain"].value_counts()
rare = counts[counts < 5].index

X["Interested Domain"] = X["Interested Domain"].replace(rare, "Other")

X["Interested Domain"].value_counts()

Interested Domain
Other                      20
Artificial Intelligence    19
Web Development            19
Cybersecurity              18
Mobile App Development     17
Database Management        16
Cloud Computing            16
Data Science               13
Machine Learning           13
Computer Graphics          13
Software Development       11
Software Engineering        5
Name: count, dtype: int64

In [ ]:
level_map = {"Weak": 0, "Average": 1, "Strong": 2}

for col in ["Python", "SQL", "Java"]:
     X[col] = X[col].map(level_map)

X.head()

   GPA        Interested Domain  Python  SQL  Java
0  3.5  Artificial Intelligence       2    2     0
1  3.2             Data Science       1    2     0
2  3.8     Software Development       2    2     1
3  3.7          Web Development       0    2     2
4  3.4            Cybersecurity       1    0     2

In [17]:
X.isnull().sum()

GPA                  0
Interested Domain    0
Python               0
SQL                  0
Java                 0
dtype: int64

In [18]:
X_encoded = pd.get_dummies(X, columns=["Interested Domain"], dtype=int)

X_encoded.shape

(180, 16)